{% set name = "langchain-anthropic" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_anthropic-{{ version }}.tar.gz
  sha256: 427e102b76a417fb5713e81e853225e7459d71fc7abdf4d86722f0e01ad43845

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.7.4,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=1.0.5,<2.0.0
    - anthropic >=0.73.0,<1.0.0
    - defusedxml <0.8.0,>=0.7.1
  run_constrained:
    - defusedxml >=0.7.1,<0.8.0

test:
  imports:
    - langchain_anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AnthropicMessages and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
