{% set name = "langchain-anthropic" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_anthropic-{{ version }}.tar.gz
  sha256: 37198413c9bde5a9e9829f13c7b9ed4870d7085e7fba9fd803ef4d98ef8ea220

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - pydantic >=2.7.4,<3.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=1.2.11,<2.0.0
    - anthropic >=0.78.0,<1.0.0
    - defusedxml <0.8.0,>=0.7.1
  run_constrained:
    - defusedxml >=0.7.1,<0.8.0

test:
  imports:
    - langchain_anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AnthropicMessages and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
