{% set name = "langchain-anthropic" %}
{% set version = "0.3.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_anthropic-{{ version }}.tar.gz
  sha256: f2c2a0382ed7992204d790ff8538448f5243f4dbb1e798256ef790c9a69033e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - pydantic <3.0.0,>=2.7.4
    - python >={{ python_min }},<4.0
    - langchain-core <1.0.0,>=0.3.68
    - anthropic <1,>=0.57.0
    - defusedxml <0.8.0,>=0.7.1
  run_constrained:
    - defusedxml >=0.7.1,<0.8.0

test:
  imports:
    - langchain_anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AnthropicMessages and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
