{% set name = "langchain-anthropic" %}
{% set version = "0.1.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_anthropic-{{ version }}.tar.gz
  sha256: cb9607fecfc0f0de49b79dd0fc066790e2877873ef753abd98d2ae38d6e0f5b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.2.17,<0.3
    - anthropic >=0.28.0,<1
    - defusedxml <0.8.0,>=0.7.1
  run_constrained:
    - defusedxml >=0.7.1,<0.8.0

test:
  imports:
    - langchain_anthropic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting AnthropicMessages and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
